<?php

declare(strict_types=1);

namespace Tests\ThreeBRS\SyliusAnalyticsPlugin\Behat\Context\Ui\Admin;

use Behat\Behat\Context\Context;
use Behat\Mink\Session;
use Symfony\Component\Routing\RouterInterface;
use Tests\ThreeBRS\SyliusAnalyticsPlugin\Behat\Context\Partials\CreateSlugTrait;
use Webmozart\Assert\Assert;

final readonly class DashboardStatisticsContext implements Context
{
    use CreateSlugTrait;

    public function __construct(
        private Session $session,
        private RouterInterface $router,
    ) {
    }

    /**
     * @Given there are multiple visits to different pages
     */
    public function thereAreMultipleVisitsToDifferentPages(): void
    {
        // This step is mainly for context - the actual visits are generated by other steps
    }

    /**
     * @Given I visit the product :productName page :count times
     */
    public function iVisitTheProductPageTimes(
        string $productName,
        int $count,
    ): void {
        $url = $this->router->generate('sylius_shop_product_show', ['slug' => $this->createSlug($productName), '_locale' => 'en_US']);

        for ($i = 0; $i < $count; ++$i) {
            $this->session->visit($url);
        }
    }

    /**
     * @Given I visit the store homepage :count times
     */
    public function iVisitTheStoreHomepageTimes(int $count): void
    {
        $url = $this->router->generate('sylius_shop_homepage', ['_locale' => 'en_US']);

        for ($i = 0; $i < $count; ++$i) {
            $this->session->visit($url);
        }
    }

    /**
     * @When I go to the admin dashboard
     */
    public function iGoToTheAdminDashboard(): void
    {
        $url = $this->router->generate('sylius_admin_dashboard');
        $this->session->visit($url);
        Assert::same(200, $this->session->getStatusCode());
    }

    /**
     * @Then I should see the most requested pages widget
     */
    public function iShouldSeeTheMostRequestedPagesWidget(): void
    {
        Assert::same(200, $this->session->getStatusCode());

        $page = $this->session->getPage();
        Assert::contains($page->getContent(), 'Most requested pages in the last');
    }

    /**
     * @Then I should see :productName page with more visits than :otherProductName
     */
    public function iShouldSeePageWithMoreVisitsThan(
        string $productName,
        string $otherProductName,
    ): void {
        Assert::same(200, $this->session->getStatusCode());

        $page = $this->session->getPage();
        $content = $page->getContent();

        // Check that the product route is mentioned in the statistics
        // The widget shows route names, not product names
        Assert::contains($content, 'sylius_shop_product_show');

        // Check that the homepage route is also present (from multiple visits)
        Assert::contains($content, 'sylius_shop_homepage');

        // Basic check that visit counts are displayed
        Assert::contains($content, '5'); // Popular T-Shirt visited 5 times
        Assert::contains($content, '3'); // Homepage visited 3 times
    }

    /**
     * @Given there are visits from different time periods
     */
    public function thereAreVisitsFromDifferentTimePeriods(): void
    {
        // This would typically involve creating test data with different timestamps
        // For now, we'll just visit some pages to generate recent data
        $this->iVisitTheStoreHomepageTimes(2);
    }

    /**
     * @Then I should see statistics for the configured number of days
     */
    public function iShouldSeeStatisticsForTheConfiguredNumberOfDays(): void
    {
        Assert::same(200, $this->session->getStatusCode());

        $page = $this->session->getPage();
        $content = $page->getContent();

        // Check that the time period is mentioned
        Assert::contains($content, 'days');
    }

    /**
     * @Then the widget should show the request log days parameter
     */
    public function theWidgetShouldShowTheRequestLogDaysParameter(): void
    {
        Assert::same(200, $this->session->getStatusCode());

        $page = $this->session->getPage();
        $content = $page->getContent();

        // Check that the configured days parameter is displayed
        Assert::contains($content, 'day');
    }
}
