# Define your own admin routes here, then load them in tests/Application/config/routes.yaml
threebrs_admin_dashboard_request_stats:
    path: /_widget/request-stats
    controller: ThreeBRS\SyliusAnalyticsPlugin\Controller\Admin\RequestStatsController
    methods: [GET]

threebrs_admin_product_request_count:
    path: /admin/_widget/product/{id}/request-count
    controller: ThreeBRS\SyliusAnalyticsPlugin\Controller\Admin\ProductRequestStatsController
    methods: [GET]