imports:
    - { resource: "app/twig_hooks/**/*.yaml" }
    - { resource: "@ThreeBRSSyliusAnalyticsPlugin/config/packages/sylius_resource.yaml" }
    - { resource: "@ThreeBRSSyliusAnalyticsPlugin/config/packages/sylius_grid.yaml" }



