# Define your own admin routes here, then load them in tests/Application/config/routes.yaml
threebrs_statistics_plugin_request_log_admin:
    resource: |
        alias: threebrs.statistics_plugin.request_log
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        grid: threebrs_statistics_plugin_request_log
    type: sylius.resource
    
threebrs_admin_dashboard_request_stats:
    path: /_widget/request-stats
    controller: ThreeBRS\SyliusAnalyticsPlugin\Controller\Admin\RequestStatsController
    methods: [GET]