#byegeeb el routes bel alias name beta3hom and loads them
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

threebrs_statistics_plugin_admin:
    resource: "@ThreeBRSSyliusAnalyticsPlugin/config/routes/admin/threebrs_statistics_plugin_request_log.yaml"
    prefix: /admin

threebrs_statistics_plugin_admin_routing_file:
    resource: "@ThreeBRSSyliusAnalyticsPlugin/config/admin_routing.yaml"
    prefix: /admin

