controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

threebrs_statistics_plugin_admin:
    resource: "@ThreeBRSSyliusAnalyticsPlugin/config/routes/admin/threebrs_statistics_plugin_request_log.yaml"
    prefix: /admin