imports:
  - { resource: ./parameters.yaml }

services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  # Whenever something (like a controller) asks for RequestLogRepositoryInterface, 
  # give it the service with ID threebrs.repository.statistics_plugin.request_log.
  ThreeBRS\SyliusAnalyticsPlugin\Repository\RequestLogRepositoryInterface: '@threebrs.repository.statistics_plugin.request_log'

  # Messenger handler
  ThreeBRS\SyliusAnalyticsPlugin\MessageHandler\LogVisitMessageHandler:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
      $channelRepository: '@sylius.repository.channel'
      $customerRepository: '@sylius.repository.customer'
      $clock: '@clock'
    tags:
      - { name: 'messenger.message_handler' }

  # Event subscriber
  ThreeBRS\SyliusAnalyticsPlugin\EventListener\RequestLoggerSubscriber:
    arguments:
      $bus: '@messenger.default_bus'
      $channelContext: '@sylius.context.channel'
      $customerContext: '@sylius.context.customer'
      $adminPath: '%sylius_admin.path_name%'
    tags:
      - { name: kernel.event_subscriber }

  # Menu listener subscriber
  ThreeBRS\SyliusAnalyticsPlugin\Menu\AdminMenuListener:
    arguments:
      $translator: '@translator'
    tags:
      - { name: kernel.event_subscriber }

  # Admin controller
  ThreeBRS\SyliusAnalyticsPlugin\Controller\Admin\RequestStatsController:
    arguments:
      $requestLogRepository: '@threebrs.repository.statistics_plugin.request_log'
      $twig: '@twig'
      $requestLogDays: '%threebrs_analytics_plugin.request_log_days%'
    tags:
      - { name: controller.service_arguments }

  # Twig extension
  ThreeBRS\SyliusAnalyticsPlugin\Twig\ProductsRequestStatsExtension:
    arguments:
      $requestLogRepository: '@threebrs.repository.statistics_plugin.request_log'
      $productRepository: '@sylius.repository.product'
    tags:
      - { name: twig.extension }

  # Console command to remove old request logs
  ThreeBRS\SyliusAnalyticsPlugin\Command\RemoveOldRequestLogsCommand:
    arguments:
      $requestLogRepository: '@threebrs.repository.statistics_plugin.request_log'
    tags: ['console.command']

