services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Messenger handler
  ThreeBRS\SyliusAnalyticsPlugin\MessageHandler\LogVisitMessageHandler: ~

  # Event subscriber
  ThreeBRS\SyliusAnalyticsPlugin\EventListener\RequestLoggerSubscriber:
    tags:
      - { name: kernel.event_subscriber }
