sylius_twig_hooks:
    hooks:
        'sylius_admin.statistics_plugin.request_log.index.content.header.title_block':
            title:
               template: '@SyliusAdmin/shared/crud/common/content/header/title_block/title.html.twig'
               configuration:
                    title: threebrs.ui.statistics_plugin.pageTitle

        'sylius_admin.dashboard.index.content.latest_statistics':
            request_log:
                template: '@ThreeBRSSyliusAnalyticsPlugin/admin/shared/request_log/_hook_widget.html.twig'
                priority: 0